#!/usr/bin/env bash
# commands that configures a firewall to block all other external request 
# except for port 2/, 443 and 80

sudo apt install ufw
sudo ufw default deny incoming 
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status
